# Generated by Django 5.2 on 2025-04-17 03:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('fund_id', models.AutoField(primary_key=True, serialize=False)),
                ('fund_name', models.CharField(max_length=255)),
                ('fund_manager_name', models.CharField(max_length=255)),
                ('fund_description', models.TextField()),
                ('nav', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_of_creation', models.DateField(default=django.utils.timezone.now)),
                ('performance', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
