# Generated by Django 5.2 on 2025-04-17 07:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('investor_id', models.AutoField(primary_key=True, serialize=False)),
                ('investor_name', models.CharField(max_length=255)),
                ('investor_email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('manager_id', models.AutoField(primary_key=True, serialize=False)),
                ('manager_name', models.CharField(max_length=255)),
                ('manager_bio', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='fund',
            name='fund_manager_name',
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('investment_id', models.AutoField(primary_key=True, serialize=False)),
                ('investment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('investment_date', models.DateField(default=django.utils.timezone.now)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='fundapp.fund')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='fundapp.investor')),
            ],
        ),
        migrations.AddField(
            model_name='fund',
            name='fund_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funds', to='fundapp.manager'),
        ),
    ]
