# Generated by Django 5.2 on 2025-04-17 07:44

from django.db import migrations, models

def set_default_manager(apps, schema_editor):
    Fund = apps.get_model('fundapp', 'Fund')
    Manager = apps.get_model('fundapp', 'Manager')

    # Get or create a default manager
    default_manager, created = Manager.objects.get_or_create(
        manager_name="Default Manager",
        defaults={"manager_bio": "This is a default manager created during migration."}
    )

    # Assign the default manager to all funds with no manager
    Fund.objects.filter(fund_manager_id__isnull=True).update(fund_manager=default_manager)

class Migration(migrations.Migration):

    dependencies = [
        ('fundapp', '0002_investor_manager_remove_fund_fund_manager_name_and_more'),
    ]

    operations = [
        migrations.RunPython(set_default_manager),
    ]