# Generated by Django 5.2 on 2025-04-21 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundapp', '0003_auto_20250417_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='fund_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
