# Generated by Django 5.2 on 2025-04-21 01:26

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundapp', '0004_alter_fund_fund_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='nav',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
